Completed issue-3-edit-entry. - Davin Phuong
dn-phuong/code-journal pull request #7
Opened 2022-03-02 23:33 UTC by dn-phuong

![Kapture 2022-03-02 at 15 27 16](https://user-images.githubusercontent.com/93227069/156467456-59157d57-9bfd-4597-a760-f73081ba762d.gif)

2022-03-02 23:38 UTC, codingcodymiller requested changes

2022-03-02 23:38 UTC, codingcodymiller commented on js/main.js
> +    data.editing = null;
You can remove this line, you already have it below the conditional, so it will always happen.

2022-03-02 23:38 UTC, codingcodymiller commented on js/main.js
> +      }
What is the purpose of this?

2022-03-02 23:38 UTC, codingcodymiller commented on js/main.js
> +    currentId = JSON.parse(currentId);
Is this to convert it to a number? You should just use `parseInt`

2022-03-03 00:42 UTC, dn-phuong commented
new test:
![Kapture 2022-03-02 at 16 41 00](https://user-images.githubusercontent.com/93227069/156473977-cb1c12e6-7447-4cdc-ad4f-862b6950d551.gif)

2022-03-03 00:43 UTC, codingcodymiller approved these changes

2022-03-03 00:44 UTC, merged